# Generated by Django 4.2.14 on 2024-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('0', 'Avatar 0'), ('1', 'Avatar 1'), ('2', 'Avatar 2'), ('3', 'Avatar 3'), ('4', 'Avatar 4'), ('5', 'Avatar 5'), ('6', 'Avatar 6'), ('7', 'Avatar 7'), ('8', 'Avatar 8'), ('9', 'Avatar 9'), ('10', 'Avatar 10'), ('11', 'Avatar 11'), ('12', 'Avatar 12'), ('13', 'Avatar 13'), ('14', 'Avatar 14'), ('15', 'Avatar 15'), ('16', 'Avatar 16')], default='0', max_length=2),
        ),
    ]
