# Generated by Django 4.2.14 on 2024-07-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('uid', models.IntegerField()),
                ('aqi', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=255)),
                ('station_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Air Quality Data',
            },
        ),
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_quality_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airqualitydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='api_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_data', to='main.apiresponse'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'air_quality_data'), name='unique_user_station'),
        ),
    ]
