# Generated by Django 4.2.14 on 2024-08-04 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dailyconditionrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconditionrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
