# Generated by Django 4.2.14 on 2024-08-04 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_dailyconditionrating_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyconditionrating',
            unique_together={('user', 'medical_condition', 'created_at')},
        ),
    ]
