# Generated by Django 4.2.14 on 2024-08-04 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_dailyconditionrating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyconditionrating',
            unique_together={('user', 'medical_condition', 'date')},
        ),
    ]
